services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: stick
      POSTGRES_PASSWORD: stick
      POSTGRES_DB: stick
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
